# This code is a Qiskit project.
#
# (C) Copyright IBM 2023.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: Lint
on: [pull_request, merge_group]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    # if: github.repository_owner == 'Qiskit'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Node.js dependencies
        run: npm ci

      - name: File metadata
        run: npm run check:metadata
      - name: Spellcheck
        run: npm run check:spelling
      - name: Internal link checker
        run: npm run check:links
      - name: Formatting
        run: npm run check:fmt
      - name: Typecheck
        run: npm run typecheck
      - name: Infrastructure tests
        run: npm test

      - name: Get all changed docs files
        id: changed-docs-files
        uses: tj-actions/changed-files@af2816c65436325c50621100d67f6e853cd1b0f1
        with:
          files: docs/**/*.{md,mdx,ipynb}
          separator: "\n"
      - name: Start local Docker preview
        if: steps.changed-docs-files.outputs.any_changed == 'true'
        run: |
          ./start &
          sleep 20
      - name: Check that pages render
        if: steps.changed-docs-files.outputs.any_changed == 'true'
        run: |
          echo "${{ steps.changed-docs-files.outputs.all_changed_files }}" > changed.txt
          npm run check-pages-render -- --from-file changed.txt
