# This code is a Qiskit project.
#
# (C) Copyright IBM 2024.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

# This Action builds the docs in pull requests so that we can view a live preview.
# It uses IBM Cloud to build the Dockerfile at the root of the repository.
#
# Due to security, this can only run on branches of qiskit/docs, i.e. not on forks.
# We skip the actions if running on a fork.

name: Tutorial preview

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "tutorials/**/*"

jobs:
  setup:
    if: |
      (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'synchronize') &&
      github.event.pull_request.head.repo.full_name == github.repository
    name: Deploy preview
    runs-on: ubuntu-latest
    environment: "Learning platform (production)"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Node.js dependencies
        run: npm ci

      - name: Get all changed files
        id: changed-files
        uses: tj-actions/changed-files@af2816c65436325c50621100d67f6e853cd1b0f1
        with:
          files: "tutorials/**/*"
          separator: " "

      - name: Upload tutorials
        run: >
          npm run tutorial:setup-preview
          --
          --prNumber ${{ github.event.number }}
          --changedFiles ${{ steps.changed-files.all_changed_files }}
        env:
          LEARNING_API_TOKEN: ${{ secrets.LEARNING_API_TOKEN }}
          LEARNING_API_URL: ${{ vars.LEARNING_API_URL }}

      - name: Comment on PR
        run: gh pr comment ${{ github.event.number }} --body "$(cat pr_message.md)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
